<a href="https://colab.research.google.com/github/NahidurRahaman/Python_Basic_To_Advance/blob/main/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
from time import process_time


In [4]:
python_list = [i for i in range(1000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0002778039999999926


In [5]:
np_array = np.array([i for i in range(1000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)


0.001421172000000137


Numpy Array

In [6]:
# List
list1 = [1,2,3,4,5,6]
print(list1)
type(list1)

[1, 2, 3, 4, 5, 6]


list

In [7]:
np_array = np.array(list1)
print(np_array)
type(np_array)

[1 2 3 4 5 6]


numpy.ndarray

In [8]:
#creating a 1 dim array
a = np.array([1,2,3,4,5,6])
print(a)


[1 2 3 4 5 6]


In [9]:
a.shape

(6,)

In [10]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
b.shape

(2, 3)

In [12]:
c = np.array([(1,2,3),(4,5,6),(7,8,9)],dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Initial Placehoder in numpy arays

In [13]:
#create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
#create a numpy array of ones
y = np.ones((3,3),dtype=int)
print(y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
#array of paticular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
# create an identity martix
a = np.eye(5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
# create numpy array with random values
c = np.random.random((3,4))

print(c)

[[0.28416228 0.47402528 0.28419389 0.55102094]
 [0.29871876 0.08245813 0.53994672 0.37836445]
 [0.71520877 0.24151649 0.54649763 0.63091984]]


In [19]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[94 76 39 94 25]
 [93 63 99 40 14]
 [24 68 70 37 93]]


In [24]:
# array of evenly spaced values --> specifying the number of vlues required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [25]:
#array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [26]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [27]:
c = np.random.randint(10,90,(5,5))
print(c)

[[64 23 11 55 10]
 [49 44 16 44 19]
 [86 78 88 51 69]
 [31 62 17 43 15]
 [35 43 77 58 40]]


In [28]:
#array dimension
print(c.shape)

(5, 5)


In [29]:
# number of dimensions
print(c.ndim)

2


In [30]:
# number of elements in an array
print(c.size)

25


In [31]:
# checking the data type of the values in the array
print(c.dtype)


int64


Mathmatical operation on a np array

In [32]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [33]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [34]:
print(a)
print(b)

[[3 6 4]
 [6 8 7]
 [6 3 9]]
[[17 11 18]
 [12 13 18]
 [14 19 18]]


In [35]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 17 22]
 [18 21 25]
 [20 22 27]]
[[-14  -5 -14]
 [ -6  -5 -11]
 [ -8 -16  -9]]
[[ 51  66  72]
 [ 72 104 126]
 [ 84  57 162]]
[[0.17647059 0.54545455 0.22222222]
 [0.5        0.61538462 0.38888889]
 [0.42857143 0.15789474 0.5       ]]


In [36]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [37]:
print(a)
print(b)

[[7 7 6]
 [0 5 4]
 [8 4 2]]
[[15 11 19]
 [15 11 16]
 [14 19 11]]


In [38]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 18 25]
 [15 16 20]
 [22 23 13]]
[[ -8  -4 -13]
 [-15  -6 -12]
 [ -6 -15  -9]]
[[105  77 114]
 [  0  55  64]
 [112  76  22]]
[[0.46666667 0.63636364 0.31578947]
 [0.         0.45454545 0.25      ]
 [0.57142857 0.21052632 0.18181818]]


Array Mainpulation

In [39]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 0 2]
 [7 4 0]]
(2, 3)


In [40]:
# transpos
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[3 7]
 [0 4]
 [2 0]]
(3, 2)


In [41]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 6 7]
 [1 5 4]]
(2, 3)


In [42]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[1 1]
 [6 5]
 [7 4]]
(3, 2)


In [43]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 6 8]
 [7 9 9]]
(2, 3)


In [44]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 6]
 [8 7]
 [9 9]]
(3, 2)
